FUNCTION Main()
   QOut("===========================")
   QOut("  FICHA DE APRESENTACAO")
   QOut("===========================")
   QOut("Nome     : Bianca Cancian")
   QOut("Cidade   : Sao Paulo")
   QOut("Curso    : Harbour/ADVPL")
   QOut("Data     : " + DToC(Date()))
   QOut("Hora     : " + Time())
   QOut("===========================")
RETURN NIL
